### ISSUE TITLE
Include RxJS 5 support

### ISSUE THREAD

**Issue by kylecordes** [cvuorinen/angular1-async-filter#5]
I was about to extend this code a bit to support RxJS 5, but then I noticed that @vfeskov already did so, in this commit on his fork:

https://github.com/vfeskov/angular1-async-filter/commit/ccbd9e2f8bb4deed7433f142755137e1850d25b7

This is a **very** helpful improvement for people mixing A1 and A2+ code in 2017, but his fork is not published to NPM. Would you consider bringing this commit in and publishing a new version?

**Comment by cvuorinen** [comment]
Sure thing, I'll pull it in and tag a new release.

**Comment by kylecordes** [comment]
Thanks!
